# neovim-bin = "/usr/bin/nvim"
# maximized = false
fork = false
frame = "full"
idle = true
mouse-cursor-icon = "arrow"
no-multigrid = false
srgb = false
tabs = true
title-hidden = true
vsync = true
wsl = false

[font]
normal = ["Sarasa Term SC Nerd"]
size = 10.0

[box-drawing]
# "font-glyph", "native" or "selected-native"
mode = "font-glyph"

[box-drawing.sizes]
default = [1, 2] # Thin and thick values respectively, for all sizes
