#!/bin/bash
# LaTeX Cleanup Script
# Removes all auxiliary files generated by LaTeX compilation

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

usage() {
    cat << USAGE
LaTeX Cleanup Script

Usage: ./clean.sh [options] [filename.tex]

Options:
    -h, --help      Show this help message
    -a, --all       Clean all LaTeX auxiliary files in current directory
    -d, --deep      Deep clean (includes PDF and synctex files)
    -n, --dry-run   Show what would be deleted without deleting

Examples:
    ./clean.sh paper.tex           # Clean files for paper.tex
    ./clean.sh -a                  # Clean all .aux, .log, etc. in directory
    ./clean.sh -d paper.tex        # Deep clean including PDF
    ./clean.sh -n -a               # Dry run to see what would be deleted

USAGE
    exit 0
}

# Default options
ALL=false
DEEP=false
DRY_RUN=false
TEXFILE=""

# Parse options
while [[ $# -gt 0 ]]; do
    case $1 in
        -h|--help)
            usage
            ;;
        -a|--all)
            ALL=true
            shift
            ;;
        -d|--deep)
            DEEP=true
            shift
            ;;
        -n|--dry-run)
            DRY_RUN=true
            shift
            ;;
        *.tex)
            TEXFILE="$1"
            shift
            ;;
        *)
            echo -e "${RED}Error: Unknown option $1${NC}"
            usage
            ;;
    esac
done

# Function to delete or show files
delete_file() {
    local file="$1"
    if [ -f "$file" ]; then
        if [ "$DRY_RUN" = true ]; then
            echo -e "${YELLOW}Would delete: $file${NC}"
        else
            rm -f "$file"
            echo -e "${GREEN}Deleted: $file${NC}"
        fi
    fi
}

# Standard auxiliary extensions
AUX_EXTENSIONS=(
    "aux"   # Auxiliary file
    "log"   # Log file
    "out"   # Hyperref outline
    "bbl"   # BibTeX bibliography
    "blg"   # BibTeX log
    "toc"   # Table of contents
    "lof"   # List of figures
    "lot"   # List of tables
    "fls"   # File list
    "fdb_latexmk"  # Latexmk database
    "synctex.gz"   # SyncTeX
    "nav"   # Beamer navigation
    "snm"   # Beamer slide notes
    "vrb"   # Beamer verbatim
)

# Deep clean extensions (including output)
DEEP_EXTENSIONS=(
    "pdf"   # PDF output
    "dvi"   # DVI output
    "ps"    # PostScript output
)

if [ "$ALL" = true ]; then
    echo -e "${YELLOW}Cleaning all LaTeX auxiliary files in current directory...${NC}"
    
    # Clean standard auxiliary files
    for ext in "${AUX_EXTENSIONS[@]}"; do
        for file in *."$ext"; do
            [ -f "$file" ] && delete_file "$file"
        done
    done
    
    # Deep clean if requested
    if [ "$DEEP" = true ]; then
        echo -e "${YELLOW}Deep cleaning (including PDFs)...${NC}"
        for ext in "${DEEP_EXTENSIONS[@]}"; do
            for file in *."$ext"; do
                [ -f "$file" ] && delete_file "$file"
            done
        done
    fi
    
elif [ -n "$TEXFILE" ]; then
    if [ ! -f "$TEXFILE" ]; then
        echo -e "${RED}Error: File '$TEXFILE' not found${NC}"
        exit 1
    fi
    
    BASENAME="${TEXFILE%.tex}"
    echo -e "${YELLOW}Cleaning files for: $TEXFILE${NC}"
    
    # Clean standard auxiliary files
    for ext in "${AUX_EXTENSIONS[@]}"; do
        delete_file "${BASENAME}.${ext}"
    done
    
    # Deep clean if requested
    if [ "$DEEP" = true ]; then
        echo -e "${YELLOW}Deep cleaning (including PDF)...${NC}"
        for ext in "${DEEP_EXTENSIONS[@]}"; do
            delete_file "${BASENAME}.${ext}"
        done
    fi
    
else
    echo -e "${RED}Error: Please specify a .tex file or use --all${NC}"
    usage
fi

if [ "$DRY_RUN" = true ]; then
    echo -e "${YELLOW}Dry run completed - no files were actually deleted${NC}"
else
    echo -e "${GREEN}Cleanup complete!${NC}"
fi
