[main]
scan_start_menu = yes
scan_env_path = no
scan_desktop = yes

[cmd/wssh]
cmd = wezterm ssh scillidan@arch
[cmd/gpt]
cmd = _sgpt {{*}}

[cmd/ecmder]
cmd = subl C:\Users\User\Usr\Git\dotfiles\.config\_windows_cmder\config\user_aliases.cmd
[cmd/ebuckets]
cmd = subl C:\Users\User\Scoop\Buckets
[cmd/edotfiles]
cmd = subl C:\Users\User\Usr\Git\dotfiles
[cmd/erofi-shortcuts]
cmd = subl C:\Users\User\Usr\Git\File\bin\_arch_rofi-shortcuts
[cmd/esnippets]
cmd = subl_snippets
# [cmd/evsix]
# cmd = vscodium "C:\Users\User\Scoop\persist\vscodium\data\user-data\User\settings.json"

[cmd/rss]
cmd = brave https://github.com/scillidan/github-search-rss/edit/main/src/RSS.ts
[cmd/feeds]
cmd = brave https://github.com/scillidan/rssTea/edit/main/feeds.txt
[cmd/startpage]
cmd = brave https://github.com/scillidan/excalith-start-page/edit/main/data/settings.json

[cmd/obsi]
cmd = obsidian://actions-uri/omnisearch/open?vault=Vault&query={{*}}
