# https://github.com/NoponyAsked/sxiv.yazi
[[mgr.prepend_keymap]]
on = ["c", "i"]
run = "plugin sxiv"
desc = "Preview images in sxiv"

# https://github.com/wylie102/duckdb.yazi
[[mgr.prepend_keymap]]
on = "H"
run = "plugin duckdb -1"
desc = "Scroll one column to the left"

[[mgr.prepend_keymap]]
on = "L"
run = "plugin duckdb +1"
desc = "Scroll one column to the right"

[[mgr.prepend_keymap]]
on = ["d", "o"]
run = "plugin duckdb -open"
desc = "open with duckdb"

[[mgr.prepend_keymap]]
on = ["d", "u"]
run = "plugin duckdb -ui"
desc = "open with duckdb ui"

#
[[mgr.prepend_keymap]]
on = ["f", "r"]
run = "plugin fr rg"
desc = "Search file by content (rg)"

[[mgr.prepend_keymap]]
on = ["f", "a"]
run = "plugin fr rga"
desc = "Search file by content (rga)"

# https://github.com/Lil-Dank/lazygit.yazi
[[mgr.prepend_keymap]]
on = ["g", "i"]
run = "plugin lazygit"
desc = "run lazygit"

# https://github.com/AnirudhG07/custom-shell.yazi
[[mgr.prepend_keymap]]
on = ["'", "\\"]
run = 'plugin custom-shell -- auto --interactive'
desc = "custom-shell as default, interactive"

# https://github.com/dedukun/bookmarks.yazi
[[mgr.prepend_keymap]]
on = ["m"]
run = "plugin bookmarks save"
desc = "Save current position as a bookmark"

[[mgr.prepend_keymap]]
on = ["b", "j"]
run = "plugin bookmarks jump"
desc = "Jump to a bookmark"

[[mgr.prepend_keymap]]
on = ["b", "d"]
run = "plugin bookmarks delete"
desc = "Delete a bookmark"

[[mgr.prepend_keymap]]
on = ["b", "D"]
run = "plugin bookmarks delete_all"
desc = "Delete all bookmarks"
