## = Yazi
## https://github.com/sxyazi/yazi
## == install
## sudo pacman -S yazi
## scoop install yazi
## == config
## https://yazi-rs.github.io/docs/configuration/overview/
## mkdir ~/.config/yazi/
## mkdir %AppData%\yazi\config
## == command
## ya pkg upgrade
## == cheatsheet
## ya pkg add gosxrgxx/flexoki-dark
## ya pkg add gosxrgxx/flexoki-light
## ya pkg add yazi-rs/plugins:toggle-pane
## ya pkg add KKV9/compress
## ya pkg add AnirudhG07/custom-shell
## ya pkg add Ape/open-with-cmd
## ya pkg add yazi-rs/plugins:piper
## ya pkg add yazi-rs/plugins:git
## ya pkg add Lil-Dank/lazygit
## ya pkg add AminurAlam/yazi-plugins:font-sample
## ya pkg add AminurAlam/yazi-plugins:preview-typst
## ya pkg add kirasok/epub-preview
## ya pkg add AminurAlam/yazi-plugins:preview-cbz
## ya pkg add boydaihungst/mediainfo
## (Arch)
## ya pkg add uhs-robert/recycle-bin
## ya pkg add yazi-rs/plugins:chmod
## ya pkg add yazi-rs/plugins:mount
## ya pkg add uhs-robert/sshfs
## ya pkg add lpnh/fr
## ya pkg add NoponyAsked/sxiv
## (Cache)
## https://github.com/boydaihungst/thunar-bulk-rename.yazi
## https://github.com/KKV9/compress.yazi
## https://github.com/grimandgreedy/ffmpeg-stats.yazi
## https://github.com/walldmtd/krita-preview.yazi
## https://github.com/wylie102/duckdb.yazi
## https://github.com/macydnah/office.yazi

[mgr]
show_hidden = true

[plugin]
prepend_fetchers = [
	{id = "git", url = "*", run = "git", group = "git" },
	{id = "git", url = "*/", run = "git", group = "git" }
]
prepend_preloaders = [
  { mime = 'font/*', run = 'font-sample' },
  { mime = 'application/ms-opentype', run = 'font-sample' },
  { url = '*.{otf,ttf,woff,woff2}', run = 'font-sample' },
	{ url = '*.typ', run = 'preview-typst' },
	# { mime = '', run = 'preview-epub' },
  # { url = '*.cb{z,r}', run = 'preview-cbz' },
	# { mime = 'audio/mpegurl', run = 'code' },
  # { mime = 'audio/*', run = 'preview-audio' },
	# { mime = "{audio,video,image}/*", run = "mediainfo" },
	# { mime = "application/subrip", run = "mediainfo" },
	# { mime = "application/postscript", run = "mediainfo" },
]
prepend_previewers = [
	{ name = "*.md", run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"' },
	{ name = "*.csv", run = 'piper -- bat -p --color=always "$1"' },
	{ name = "*/", run = 'piper -- eza -TL=3 --color=always --icons=always --group-directories-first --no-quotes "$1"' },
	# { name = "*", run = 'piper -- hexyl --border=none --terminal-width=$w "$1"' },
  { mime = 'font/*', run = 'font-sample' },
  { mime = 'application/ms-opentype', run = 'font-sample' },
  { url = '*.{otf,ttf,woff,woff2}', run = 'font-sample' },
	{ url = '*.typ', run = 'preview-typst' },
	{ mime = "application/epub+zip", run = "epub-preview" },
	# { mime = '', run = 'preview-epub' },
  # { url = '*.cb{z,r}', run = 'preview-cbz' },
	# { mime = 'audio/mpegurl', run = 'code' },
  # { mime = 'audio/*', run = 'preview-audio' },
	# { mime = "{audio,video,image}/*", run = "mediainfo" },
	# { mime = "application/subrip", run = "mediainfo" },
	# { mime = "application/postscript", run = "mediainfo" },
]

[tasks]
# image_alloc = 1073741824 # = 1024*1024*1024 = 1024MB
