[mgr]
show_hidden = true

[plugin]
prepend_fetchers = [
	## https://github.com/yazi-rs/plugins/tree/main/git.yazi
	{id = "git", url = "*", run = "git", group = "git" },
	{id = "git", url = "*/", run = "git", group = "git" }
]
prepend_preloaders = [
	## https://github.com/AminurAlam/yazi-plugins/tree/main/font-sample.yazi
  { mime = 'font/*', run = 'font-sample' },
  { mime = 'application/ms-opentype', run = 'font-sample' },
  { url = '*.{otf,ttf,woff,woff2}', run = 'font-sample' },
	## https://github.com/AminurAlam/yazi-plugins/tree/main/preview-typst.yazi
	{ url = '*.typ', run = 'preview-typst' },
	## https://github.com/AminurAlam/yazi-plugins/tree/main/preview-epub.yazi
	# { mime = '', run = 'preview-epub' },
  ## https://github.com/AminurAlam/yazi-plugins/tree/main/preview-cbz.yazi
  # { url = '*.cb{z,r}', run = 'preview-cbz' },
	## https://github.com/AminurAlam/yazi-plugins/tree/main/preview-audio.yazi
	# { mime = 'audio/mpegurl', run = 'code' },
  # { mime = 'audio/*', run = 'preview-audio' },
	## https://github.com/boydaihungst/mediainfo.yazi
	# { mime = "{audio,video,image}/*", run = "mediainfo" },
	# { mime = "application/subrip", run = "mediainfo" },
	# { mime = "application/postscript", run = "mediainfo" },
]
prepend_previewers = [
	## https://github.com/yazi-rs/plugins/tree/main/piper.yazi
	{ name = "*.md", run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"' },
	{ name = "*.csv", run = 'piper -- bat -p --color=always "$1"' },
	{ name = "*/", run = 'piper -- eza -TL=3 --color=always --icons=always --group-directories-first --no-quotes "$1"' },
	# { name = "*", run = 'piper -- hexyl --border=none --terminal-width=$w "$1"' },
	## https://github.com/AminurAlam/yazi-plugins/tree/main/font-sample.yazi
  { mime = 'font/*', run = 'font-sample' },
  { mime = 'application/ms-opentype', run = 'font-sample' },
  { url = '*.{otf,ttf,woff,woff2}', run = 'font-sample' },
	## https://github.com/AminurAlam/yazi-plugins/tree/main/preview-typst.yazi
	{ url = '*.typ', run = 'preview-typst' },
	## https://github.com/kirasok/epub-preview.yazi
	{ mime = "application/epub+zip", run = "epub-preview" },
	## https://github.com/AminurAlam/yazi-plugins/tree/main/preview-epub.yazi
	# { mime = '', run = 'preview-epub' },
  ## https://github.com/AminurAlam/yazi-plugins/tree/main/preview-cbz.yazi
  # { url = '*.cb{z,r}', run = 'preview-cbz' },
	## https://github.com/AminurAlam/yazi-plugins/tree/main/preview-audio.yazi
	# { mime = 'audio/mpegurl', run = 'code' },
  # { mime = 'audio/*', run = 'preview-audio' },
	## https://github.com/boydaihungst/mediainfo.yazi
	# { mime = "{audio,video,image}/*", run = "mediainfo" },
	# { mime = "application/subrip", run = "mediainfo" },
	# { mime = "application/postscript", run = "mediainfo" },
]

[tasks]
# image_alloc = 1073741824 # = 1024*1024*1024 = 1024MB
