# https://gist.github.com/3ayazaya/d87c70c5f30a6e28f15dfc84ca95fc68

format = "$all$directory$character"

[character]
success_symbol = "[λ](white)"
error_symbol = "[λ](red)"
vicmd_symbol = "[λ](cyan)"

[directory]
style = "green"
read_only = " ro"

[memory_usage]
symbol = "memory "

[package]
symbol = "pkg "

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "-"
deleted = "x"

[git_branch]
symbol = "git "

[typst]
symbol = "typ "
format = "$symbol $version"

[lua]
symbol = "lua "
format = "$symbol $version"

[python]
symbol = "py "
format = '${symbol} (${version} )(\($virtualenv\) )'
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"

[conda]
symbol = "conda "
format = "$symbol $version"

[rust]
symbol = "rs "
format = "$symbol $version"

[nodejs]
symbol = "nodejs "
format = "$symbol $version"
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]

[ruby]
symbol = "rb "
format = "$symbol $version"

[golang]
symbol = "go "
format = "$symbol $version"

[java]
symbol = "java "
format = "$symbol $version"

[cmake]
symbol = "cmake "
format = "$symbol $version"
