require("apidocs").setup({
	data_folder = vim.fn.stdpath("data") .. "/apidocs",
	picker = "snacks",
	ensure_install = {
		-- "bash",
		-- "css",
		-- "git",
		-- "html",
		-- "http",
		-- "javascript",
		-- "jq",
		-- "latex",
		-- "less~4",
		-- "love",
		-- "lua~5.3",
		-- "nextjs",
		-- "python~3.12",
		-- "ramda",
		-- "sass",
		-- "sqlite",
		-- "svg",
		-- "zsh",
		-- "node~24_lts",
		-- "react~18",
		-- "react_bootstrap",
		-- "react_native",
		-- "react_router",
		-- "tailwindcss~3",
		-- "typescript~5.1",
	},
})
