require("lsp-setup").setup({
  servers = {
    bashls = {},
    cssls = {},
    eslint = {},
    harper_ls = {
      filetypes = { "markdown", "md" },
      userDictPath = "",
      fileDictPath = "",
      linters = {
        SpellCheck = false,
        SpelledNumbers = false,
        AnA = true,
        SentenceCapitalization = false,
        UnclosedQuotes = true,
        WrongQuotes = false,
        LongSentences = true,
        RepeatedWords = true,
        Spaces = true,
        Matcher = true,
        CorrectNumberSuffix = true,
      },
      codeActions = {
        ForceStable = false,
      },
      markdown = {
        IgnoreLinkTitle = true,
      },
      diagnosticSeverity = "hint",
      dialect = "American",
    },
    html = {},
    jsonls = {},
    lua_ls = {},
    marksman = {},
    pyright = {},
    taplo = {},
    texlab = {},
    tinymist = {},
    yamlls = {},
    -- emmet_language_server = {},
    -- jdtls = {},
    -- nextls = {},
    -- tailwindcss = {},
    -- typescript_language_server = {},
  },
})
