require("snacks").setup({
	animate = { enabled = false },
	bigfile = { enabled = false },
	bufdelete = { enabled = false },
	dashboard = { enabled = false },
	debug = { enabled = false },
	dim = { enabled = false },
	explorer = { enabled = false },
	git = { enabled = false },
	gitbrowse = { enabled = false },
	image = { enabled = false },
	indent = { enabled = false },
	input = { enabled = false },
	layout = { enabled = false },
	lazygit = { enabled = false },
	notifier = { enabled = false },
	notify = { enabled = false },
	profiler = { enabled = false },
	quickfile = { enabled = false },
	rename = { enabled = false },
	scope = { enabled = false },
	scratch = { enabled = false },
	scroll = { enabled = false },
	statuscolumn = { enabled = false },
	terminal = { enabled = false },
	toggle = { enabled = false },
	util = { enabled = false },
	win = { enabled = false },
	words = { enabled = false },
	zen = { enabled = false },
	picker = {
		enabled = true,
		ui_select = true,
		layout = {
			layout = {
				box = "vertical",
				backdrop = false,
				row = -1,
				width = 0,
				height = 0.5,
				border = "none",
				title = " {title} {live} {flags}",
				title_pos = "left",
				{ win = "input", height = 1, border = "none" },
				{
					box = "horizontal",
					{ win = "list", border = "none" },
					{ win = "preview", title = "{preview}", width = 0.8, border = "none" },
				},
			},
		},
	},
})
