matches:
  - regex: ":hi\\((?P<person>.*)\\)"
    replace: "Hi {{person}}!"
  # - regex: "=sum\\((?P<num1>.*?),(?P<num2>.*?)\\)"
  #   replace: "{{result}}"
  #   vars:
  #     - name: result
  #       type: shell
  #       params:
  #         cmd: "expr $ESPANSO_NUM1 + $ESPANSO_NUM2"
  - trigger: ":what"
    replace: "What is $|$? Using metaphors and rhetoric helps me understand."
  - trigger: ":diff"
    replace: "What is the difference between $|$?"
  - trigger: ":by"
    replace: "Write by GPT-4o mini?????, scillidan??"
  - trigger: ":cheat"
    replace: "https://scillidan.github.io/cheat/$|$.html"
  - trigger: ":ce"
    replace: "```sh$|$\n```"
  - trigger: ":gc"
    replace: "git clone --depth=1 "
  - trigger: ":pv"
    replace: "python -m venv .venv\n.venv\\Scripts\\activate.bat"
  - trigger: ":uv"
    replace: "uv venv\n.venv\\Scripts\\activate.bat"
  - trigger: ":torch"
    replace: "uv pip install torch --index-url https://download.pytorch.org/whl/cu121"
  - trigger: ":yas"
    replace: "yay -S --noconfirm"
  - trigger: ":dup"
    replace: "^(.*)(\\r?\\n\\1)+$"
  - trigger: ":cjk"
    replace: "[^\\x00-\\xff]+"
