matches:
  - trigger: ":now"
    replace: "{{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%H:%M"

  - trigger: ":ce"
    replace: "```sh$|$\n```"

  - trigger: ":sh"
    replace: "#!/usr/bin/env bash"
