matches:
  # Chat
  - trigger: ":diff"
    replace: "What is the difference between "

  - trigger: ":howmatch"
    replace: "Used regex, how to match string `$|$`"

  # Write
  - trigger: ":ce"
    replace: "```sh$|$\n```"

  - trigger: ":aut"
    form: |
      Authors: [[author]]🧙‍♂️, scillidan🤡
    form_fields:
      author:
        type: choice
        values:
          - DeepSeek
          - GPT-4o mini
          - mistral.ai
          - perplexity.ai
        default: GPT-4o mini

  - trigger: ":by"
    form: |
      [[by]]
    form_fields:
      by:
        type: choice
        values:
          - '[Gemma3 12B]'
          - '[Gemma3 Translator 4B]'
          - '[Qwen3 14B]'
          - '[perplexity.ai]'
          - '[GPT-4o mini]'
        default: '[perplexity.ai]'

  # Commit
  - trigger: ":thks"
    replace: "Thanks for your review!"

  - trigger: ":prdone"
    replace: "Completed the PR to bucket Extras$|$ and clean up"

  - trigger: ":opps"
    replace: "chore: opps!"

  - trigger: ":stars"
    replace: "It has $|$ Stars on Github."
