matches:
  # Chat
  - trigger: ":diff"
    replace: "What is the difference between "
  - trigger: ":howmatch"
    replace: "Used regex, how to match string `$|$`"
  # Write
  - trigger: ":ce"
    replace: "```sh$|$\n```"
  - trigger: ":aut"
    form: |
      Authors: [[author]]🧙‍♂️, scillidan🤡
    form_fields:
      author:
        type: choice
        values:
          - DeepSeek
          - MiniMax-M2.1
          - perplexity.ai
          - mistral.ai
        default: DeepSeek
  - trigger: ":by"
    form: |
      [[by]]
    form_fields:
      by:
        type: choice
        values:
          - '[Gemma3 12B]'
          - '[Gemma3 Translator 4B]'
          - '[Qwen3 14B]'
          - '[perplexity.ai]'
        default: '[perplexity.ai]'
  - trigger: ":cmt"
    form: |
      [[commit]]
    form_fields:
      commit:
        type: choice
        values:
          - 'chore: .'
          - 'ci: code simplified'
          - 'doc: update'
          - 'It has $|$ Stars on Github.'
          - 'Thanks for your review!'
          - 'completed the PR to bucket Extras$|$; clean up'
