[colors.primary]
background = "0x000000"
foreground = "0xf8fafc"

[colors.normal]
black = "0x000000"
red = "0xef4444"
green = "0x00ff00"
yellow = "0xfde047"
blue = "0x2563eb"
magenta = "0xff00ff"
cyan = "0x22d3ee"
white = "0xf8fafc"

[colors.cursor]
text = "#1a1a1a"
cursor = "#f8fafc"
